//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;
    using System.ComponentModel.DataAnnotations.Schema;

        public partial class AccessTable
    {
        public int AccessID { get; set; }
        [Display(Name = "Name")]
        public string AccessName { get; set; }
        [Display(Name = "Photo")]
        public string AccessPhoto { get; set; }
        [Display(Name = "Type")]
        public string AccessType { get; set; }
        [Display(Name = "Color")]
        public string AccessColor { get; set; }
        [Display(Name = "Season")]
        public string AccessSeason { get; set; }
        [Display(Name = "Occasion")]
        public string AccessOccasion { get; set; }
    }
}
