//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class BottomsTable
    {
        public int BottomsID { get; set; }
        public string BottomsName { get; set; }
        public string BottomsPhoto { get; set; }
        public string BottomsType { get; set; }
        public string BottomsColor { get; set; }
        public string BottomsSeason { get; set; }
        public string BottomsOccasion { get; set; }
    }
}
