//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class DressesTable
    {
        public int DressesID { get; set; }
        public string DressesName { get; set; }
        public string DressesPhoto { get; set; }
        public string DressesType { get; set; }
        public string DressesColor { get; set; }
        public string DressesSeason { get; set; }
        public string DressesOccasion { get; set; }
    }
}
