//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class ShoesTable
    {
        public int ShoesID { get; set; }
        public string ShoesName { get; set; }
        public string ShoesPhoto { get; set; }
        public string ShoesType { get; set; }
        public string ShoesColor { get; set; }
        public string ShoesSeason { get; set; }
        public string ShoesOccasion { get; set; }
    }
}
