//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class SwimTable
    {
        public int SwimTableID { get; set; }
        public string SwimName { get; set; }
        public string SwimPhoto { get; set; }
        public string SwimType { get; set; }
        public string SwimColor { get; set; }
        public string SwimSeason { get; set; }
        public string SwimOccasion { get; set; }
    }
}
