//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GoVintage.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class VintageWardrobeEntities : DbContext
    {
        public VintageWardrobeEntities()
            : base("name=VintageWardrobeEntities")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<AccessTable> AccessTables { get; set; }
        public virtual DbSet<BottomsTable> BottomsTables { get; set; }
        public virtual DbSet<DressesTable> DressesTables { get; set; }
        public virtual DbSet<ShoesTable> ShoesTables { get; set; }
        public virtual DbSet<SwimTable> SwimTables { get; set; }
        public virtual DbSet<TopsTable> TopsTables { get; set; }
    }
}
